mcritweb/views/cross_compare.py
import json

def get_sample_to_job_id(job_info):
    return json.loads(job_info.payload["params"])['0']


def score_to_color(score):
    if score >= 90:
        return "0080ff"  # dark blue
    elif score >= 80:
        return "00ffff"  # cyan
    elif score >= 70:
        return "00ff00"  # green 
    elif score >= 60:
        return "c0ff00"  # lime
    elif score >= 50:
        return "ffff00"  # yellow
    elif score >= 40:
        return "ffc000"  # orange
    elif score >= 30:
        return "ff8000"  # dark orange
    elif score >= 20:
        return "ff4000"  # red-orange
    elif score >= 10:
        return "ff0000"  # red
    elif score > 0:
        return "444444"  # light grey
    else:
        return "222222"  # dark grey / background

mcritweb/views/data.py
import os
import re
import datetime
import hashlib
import logging
from datetime import datetime
from mcrit.client.McritClient import McritClient
from mcrit.storage.MatchingResult import MatchingResult
from mcrit.storage.MatchedFunctionEntry import MatchedFunctionEntry
from mcrit.storage.FunctionEntry import FunctionEntry
from mcrit.storage.SampleEntry import SampleEntry
from mcrit.storage.UniqueBlocksResult import UniqueBlocksResult
from mcrit.queue.LocalQueue import Job
from smda.common.SmdaReport import SmdaReport
from flask import current_app, Blueprint, render_template, request, redirect, url_for, Response, flash, session, send_from_directory, json

from mcritweb.db import UserColumnSettings, UserFilters
from mcritweb.views.analyze import query as analyze_query
from mcritweb.views.utility import get_server_url, get_server_token, get_username, mcrit_server_required, parseBitnessFromFilename, parseBaseAddrFromFilename, get_matches_node_colors, parse_integer_query_param, parse_integer_list_query_param, parse_checkbox_query_param, parse_str_query_param, get_session_user_id
from mcritweb.views.pagination import Pagination
from mcritweb.views.cross_compare import get_sample_to_job_id, score_to_color
from mcritweb.views.authentication import visitor_required, contributor_required
from mcritweb.views.ScoreColorProvider import ScoreColorProvider
from mcritweb.views.MatchReportRenderer import MatchReportRenderer

bp = Blueprint('data', __name__, url_prefix='/data')

################################################################
# Helper functions
################################################################

def load_cached_result(app, job_id):
    matching_result = {}
    cache_path = os.sep.join([app.instance_path, "cache", "results"])
    for filename in os.listdir(cache_path):
        if job_id in filename and filename.endswith("json"):
            with open(cache_path + os.sep + filename, "r") as fin:
                matching_result = json.load(fin)
    return matching_result


def cache_result(app, job_info, matching_result):
    # TODO potentially implement a cache control that manages maximum allowed cache size?
    if job_info.result is not None:
        cache_path = os.sep.join([app.instance_path, "cache", "results"])
        timestamped_filename = datetime.utcnow().strftime(f"%Y%m%d-%H%M%S-{job_info.job_id}.json")
        with open(cache_path + os.sep + timestamped_filename, "w") as fout:
            json.dump(matching_result, fout, indent=1)


def create_match_diagram(app, job_id, matching_result, filtered_family_id=None, filtered_sample_id=None, filtered_function_id=None):
    cache_path = os.sep.join([app.instance_path, "cache", "diagrams"])
    filter_suffix = ""
    if filtered_family_id is not None:
        filter_suffix = f"-famid_{filtered_family_id}"
    elif filtered_sample_id is not None:
        filter_suffix = f"-samid_{filtered_sample_id}"
    elif filtered_function_id is not None:
        filter_suffix = f"-funid_{filtered_function_id}"
    output_path = cache_path + os.sep + job_id + filter_suffix + ".png"
    if not os.path.isfile(output_path):
        renderer = MatchReportRenderer()
        renderer.processReport(matching_result)
        image = renderer.renderStackedDiagram(filtered_family_id=filtered_family_id, filtered_sample_id=filtered_sample_id, filtered_function_id=filtered_function_id)
        image.save(output_path)
        print("stored new MCRIT diagram:", output_path)

# https://stackoverflow.com/a/39842765
# https://stackoverflow.com/a/26972238
# https://flask.palletsprojects.com/en/1.0.x/api/#flask.send_from_directory
@bp.route('/diagrams/<path:filename>')
def diagram_file(filename):
    cache_path = os.sep.join([current_app.instance_path, "cache", "diagrams"])
    return send_from_directory(cache_path, filename)


################################################################
# Import + Export
################################################################

@bp.route('/import',methods=('GET', 'POST'))
@mcrit_server_required
@contributor_required
def import_view():
    if request.method == 'POST':
        f = request.files.get('file', '')
        client = McritClient(mcrit_server=get_server_url(), apitoken=get_server_token(), username=get_username())
        session["last_import"] = client.addImportData(json.load(f))
    return render_template("import.html")

@bp.route('/import_complete')
@contributor_required
def import_complete():
    import_results = session.pop('last_import',{})
    if import_results:
        return render_template("import_complete.html", results=import_results)
    else:
        flash("This doesn't seem to be valid MCRIT data in JSON format", category='error')
        return render_template("import.html")


@bp.route('/export',methods=('GET', 'POST'))
@mcrit_server_required
@contributor_required
def export_view():
    if request.method == 'POST':
        requested_samples = request.form['samples']
        client = McritClient(mcrit_server=get_server_url(), apitoken=get_server_token(), username=get_username())
        if requested_samples == "":
            export_file = json.dumps(client.getExportData())
            return Response(
                export_file,
                mimetype='application/json',
                headers={"Content-disposition":
                        "attachment; filename=export_all_samples.json"})
        # NOTE it might be nice to allow [<number>, <number>-<number>, ...] to enable 
        # spans of consecutive sample_ids
        elif re.match("^\d+(?:[\s]*,[\s]*\d+)*$", requested_samples):
            sample_ids = [int(sample_id.strip()) for sample_id in requested_samples.split(',')]
            export_file = json.dumps(client.getExportData(sample_ids))
            return Response(
                export_file,
                mimetype='application/json',
                headers={"Content-disposition":
                        "attachment; filename=export_samples.json"})
        else:
            flash('Please use a comma-separated list of sample_ids in your export request.', category='error')
            return render_template("export.html")
    return render_template("export.html")

@bp.route('/specific_export/<type>/<item_id>')
@mcrit_server_required
@contributor_required
def specific_export(type, item_id):
    client = McritClient(mcrit_server=get_server_url(), apitoken=get_server_token(), username=get_username())
    if type == 'family':
        samples = client.getSamplesByFamilyId(item_id)
        sample_ids = [x.sample_id for x in samples.values()]
        export_file = json.dumps(client.getExportData(sample_ids))
        return Response(
            export_file,
            mimetype='application/json',
            headers={"Content-disposition":
                    "attachment; filename=export_family_"+str(item_id)+".json"})
    if type == 'samples':
        sample_ids = []
        sample_entry = client.getSampleById(item_id)
        if sample_entry:
            sample_ids.append(sample_entry.sample_id)
        export_file = json.dumps(client.getExportData(sample_ids))
        return Response(
            export_file,
            mimetype='application/json',
            headers={"Content-disposition":
                    "attachment; filename=export_samples.json"})

################################################################
# Direct Function Matching
################################################################

@bp.route('/matches/function/<function_id_a>/<function_id_b>')
@mcrit_server_required
@visitor_required
def match_functions(function_id_a, function_id_b):
    client = McritClient(mcrit_server=get_server_url(), apitoken=get_server_token(), username=get_username())
    if client.isFunctionId(function_id_a) and client.isFunctionId(function_id_b):
        match_info = client.getMatchFunctionVs(function_id_a, function_id_b)
        print(match_info)
        function_entry = FunctionEntry.fromDict(match_info["function_entry_a"])
        pichash_matches_a = client.getMatchesForPicHash(function_entry.pichash, summary=True)
        sample_entry_a = SampleEntry.fromDict(match_info["sample_entry_a"])
        other_function_entry = FunctionEntry.fromDict(match_info["function_entry_b"])
        sample_entry_b = SampleEntry.fromDict(match_info["sample_entry_b"])
        pichash_matches_b = client.getMatchesForPicHash(other_function_entry.pichash, summary=True)
        matched_function_entry = MatchedFunctionEntry(match_info["match_entry"]["fid"], match_info["match_entry"]["num_bytes"], match_info["match_entry"]["offset"], match_info["match_entry"]["matches"])
        node_colors = get_matches_node_colors(function_id_a, function_id_b)
        return render_template(
            "result_compare_function_vs.html",
            entry_a=function_entry,
            entry_b=other_function_entry,
            sample_entry_a=sample_entry_a,
            sample_entry_b=sample_entry_b,
            pichash_matches_a=pichash_matches_a,
            pichash_matches_b=pichash_matches_b,
            match_result=matched_function_entry,
            node_colors=json.dumps(node_colors)
        )
    flash("One of the function_ids is not valid.", category='error')
    return render_template("index.html")

################################################################
# Result presentation
################################################################

@bp.route('/result/<job_id>')
@mcrit_server_required
@visitor_required
# TODO:  refactor, simplify
def result(job_id):
    client = McritClient(mcrit_server=get_server_url(), apitoken=get_server_token(), username=get_username())
    # check if we have the respective report already locally cached
    result_json = load_cached_result(current_app, job_id)
    job_info = client.getJobData(job_id)
    if not result_json:
        # otherwise obtain result report from remote
        result_json = client.getResultForJob(job_id)
        if result_json:

mcritweb/templates/admin_server.html
{% extends 'base.html' %}
{% block title%}
Server settings
{% endblock %}
{% block content %}
<h1>Server Management</h1>

<h3>Server Parameters:</h3>

<table>
    <tr>
        <th>Parameter</th>
        <th>Value</th>
    </tr>
    <tr>
        <td>Server UUID:</td>
        <td>{{ server_info.server_uuid }}</td>
    </tr>
    <tr>
        <td>Registration Token: </td>
        <td>{{ server_info.registration_token }}&nbsp;<i class="fa-regular fa-copy" onclick="copyRegistrationUrl()"></i></td>
    </tr>
    <tr>
        <td>Operation Mode: </td>
        <td>{{ operation_mode }}</td>
    </tr>
    <tr>
        <td>DB MCRIT Web Version: </td>
        <td>{{ server_info.server_version }}</td>
    </tr>
    <tr>
        <td>Running MCRIT Web Version: </td>
        <td>{{ running_version }}</td>
    </tr>
    <tr>
        <td>Running MCRIT Backend Version: </td>
        <td>{{ mcrit_version }}</td>
    </tr>
</table>

<h3>Maintenance:</h3>
<p>Schedule jobs for various Maintenance functionality. Note that depending on your database size, some of these operations may take some time.</p>

<form action = "{{ url_for('admin.schedule_recalc_pichashes') }}" method='post'>
    <button type="submit" class="btn btn-primary">Recalculate PicHashes</button>
</form>
<form action = "{{ url_for('admin.schedule_recalc_minhashes') }}" method='post'>
    <button type="submit" class="btn btn-primary">Recalculate MinHashes</button>
</form>
<form action = "{{ url_for('admin.schedule_rebuild_index') }}" method='post'>
    <button type="submit" class="btn btn-primary">Rebuild MinHash Index</button>
</form>

<h3>Change Backend Server:</h3>

<form action = "{{ url_for('admin.change_server') }}" method='post'>
    <div class="form-group">
        <label for="server">mcrit-server</label>
        <input type="url" name='mcrit_server_url' class="form-control" id="mcrit_server_url" aria-describedby="Enter a URL for a MCRIT server" value={{ server_info.url }} required>
        <input type="text" name='mcrit_server_token' class="form-control" id="mcrit_server_token" aria-describedby="Enter the (optional) AUTH_TOKEN for this MCRIT server" value={{ server_info.server_token }}>
    </div>
    <button type="submit" class="btn btn-primary">Confirm change</button>
</form>

<h3>Reset server:</h3>
<p>Warning: This will fully reset the backend including its database as well as cached data in the frontend.</p>

<form action = "{{ url_for('admin.reset_server') }}" method='post'>
    <div class="form-group">
        <label for="server">Type "RESET" to confirm the action.</label>
        <input type="text" name='reset_server' class="form-control" id="reset_server" aria-describedby="Enter confirmation string" value="" placeholder="RESET" pattern="^RESET$" required>
    </div>
    <button type="submit" class="btn btn-primary">Reset Server</button>
</form>

<script>
    function copyRegistrationUrl() {
      var js_token = "{{ server_info.registration_token }}";
      var_register_url = "{{ url_for('authentication.register', _external=True) }}";
      // Copy the text inside the text field
      navigator.clipboard.writeText(var_register_url + "?token=" + js_token);
      // Alert the copied text
      alert("Copied Registration URL!");
    }
    </script>

{% endblock %}

mcritweb/templates/compare_submit_query.html
{% extends 'base.html' %}
{% block title%}
Compare Submit Query
{% endblock %}
{% block content %}
  <h1>Compare Submit Query</h1>
{% endblock %}

mcritweb/templates/import_complete.html
{% extends 'base.html' %}
{% block title%}
Statistics
{% endblock %}
{% block content %}
  <h1>Import completed</h1>
  <table class="table table-sm table-borderless" style="width:50%;">
    {% if results %}
    {% for key in results %}
    <tr>
      <th valign="middle">{{ key }}</td>
      <td valign="middle">{{ results[key] }}</td>
    </tr>
    {% endfor %}
    {% endif %}
  </table>
{% endblock %}

mcritweb/templates/index.html
{% from 'table/table.html' import minijob_table, minisample_table %}
{% from 'table/job_row.html' import job_row_std_js %}

{% extends 'base.html' %}
{% block title%}
Home
{% endblock %}
{% block content %}

{% if g.user %}
  <h1>Welcome {{g.user.username}}
  </h1>
    <p>
      You are: {{g.user.role}}
      {% if g.user.role == "admin" %}
      <i class="fas fa-crown"></i>
      {% endif %}
    </p>
  {% if g.user.role == 'pending' %}
    <h4>Please wait for an admin to assign you a role</h4>
  {% else %}
  <br />
  <h3>Latest Sample Additions</h3>
  {{ minisample_table(latest_samples) }}
  <br /><br />
  <h3>Latest Matching Jobs</h3>
  {{ minijob_table(jobs, table_id="matching_jobs", families_by_id=families, samples_by_id=samples) }}
  {% endif %}
{% endif %}
  
{% endblock %}

mcritweb/templates/job_in_progress.html
{% from 'table/column_table.html' import job_column_table %}

{% extends 'base.html' %}
{% block title%}
Progress Report for Job: {{ job_info.job_id }}
{% endblock %}
{% block style %}
{% endblock %}
{% block content %}
<h1>Job in Progress: {{ job_info.parameters }}</h1>

{{ job_column_table(job_info, show_progress=True, show_duration=False) }}

{% endblock %}

mcritweb/templates/job_overview.html
{% from 'table/table.html' import job_table %}
{% from 'table/job_row.html' import job_row_std_js %}
{% from 'table/column_table.html' import job_column_table %}

{% extends 'base.html' %}
{% block title%}
Overview for Job: {{ job_info.job_id }}
{% endblock %}
{% block style %}
{% if (auto_refresh > 0) and (not job_info.finished_at) %}
<meta http-equiv="refresh" content="{{ auto_refresh }}">
{% endif %}

{{ job_row_std_js() }}

{% endblock %}
{% block content %}
<h1>Job overview: {{ job_info.parameters }}</h1>

{{ job_column_table(job_info, show_progress=True) }}


{% if child_jobs %}
    {{ job_table(child_jobs, families_by_id=families, samples_by_id=samples) }}
{% endif %}

{% endblock %}

mcritweb/templates/register.html
{% extends 'base.html' %}
{% block title%}
Register
{% endblock %}
{% block content %}
<center>
  <form method='post'>
    <h3>Define User Details:</h3>
    <div class="form-group">
      <input name='username' class="form-control" id="username" aria-describedby="usernameHelp" placeholder="Enter username" title="Allowed: ^(?=[a-zA-Z0-9._]{3,20}$)(?!.*[_.]{2})[^_.].*[^_.]$ -- i.e. 3-20 chars, alphanumeric with single dots and underscores in the middle" pattern="^(?=[a-zA-Z0-9._]{3,20}$)(?!.*[_.]{2})[^_.].*[^_.]$", required autofocus>
    </div>
    <div class="form-group">
      <input type="password" name='inputPassword1' class="form-control" id="inputPassword1" placeholder="Enter password" required>
    </div>
    <div class="form-group">
        <input type="password" class="form-control" name="inputPassword2" id="inputPassword2" placeholder="Confirm password" required>
    </div>
    {% if is_registration_token_required %}
      <div class="form-group">
        <input class="form-control" name="registrationToken" id="registrationToken" placeholder="Enter registration token" value="{{ query_token }}" required>
      </div>
    {% endif %}
      {% if g.first_user %}
      <h3>Define Server Details:</h3>
      <div class="form-group">
        <label for="server">Choose MCRIT backend server:</label>
        <input type="url" name='url' class="form-control" id="server" aria-describedby="serverHelp" value="{{ default_mcrit_server }}" required>
        <label for="set-server-token">Enter the (optional) AUTH_TOKEN for this MCRIT server:</label>
        <input type="text" name='mcritServerToken' class="form-control" id="mcritServerToken" aria-describedby="Enter the (optional) AUTH_TOKEN for this MCRIT server" value="">
      </div>
      <div class="form-group">
        <label for="set-registration-token">Optional registration token (replace or clear if other or no token desired):</label>
        <input name='setRegistrationToken' class="form-control" id="set-registration-token" aria-describedby="tokenHelp" value="{{ proposed_registration_token }}" pattern="^[a-zA-Z0-9._\-]{3,36}$">
      </div>
    <h3>Define Operation Mode:</h3>
    <div class="form-group form-check">
        <input class="form-check-input" type="radio" name="operationMode" id="radio_single" value="single" checked>
        <label class="form-check-label" for="radio_single">
          Single user
        </label>
    </div>
    <div class="form-group form-check">
        <input class="form-check-input" type="radio" name="operationMode" id="radio_multi" value="multi">
        <label class="form-check-label" for="radio_multi">
          Multi user
        </label>
    </div>
    {% endif %}
    <button type="submit" class="btn btn-primary">Register</button>
</form>
</center>

{% endblock %}

mcritweb/templates/result_compare_function.html
{% from 'table/pagination_widget.html' import pagination_widget, pagination_js, set_pagination_params %}
{% from 'table/column_table.html' import sample_column_table, matching_result_job_column_table %}
{% from 'table/matching_statistics_table.html' import matching_statistics_table %}
{% from 'table/links.html' import format_pichash, format_offset, format_family_name, format_family_id, format_sample_id, format_function_id %}

{% extends 'base.html' %}
{% block title%}
Results for Job: {{ job_info.job_id }}
{% endblock %}
{% block style %}
{{ pagination_js() }}
{% endblock %}
{% block content %}
<h1>Results for Job: {{ matching_result.method }}</h1>
<p>Showing matches against family: {{ matching_result.getFamilyNameByFamilyId(famid) }}</p>

{{ matching_result_job_column_table(job_info) }}


<h3>Input Sample</h3>
{{ sample_column_table(("Reference Sample", matching_result.reference_sample_entry)) }}

<p><a href="{{'/data/linkhunt/' + job_info.job_id}}">Go to linkhunt report</a></p>

<p><a href="{{ url_for(request.endpoint, **request.view_args) }}#family-matches">back to all family overview</a></p>

{% if not matching_result.is_query %}
<h3>MCRIT Diagram</h3>
<p>Showing: foreign family match frequency, library matches, best foreign family match scores.</p>
<img src="{{ url_for('data.diagram_file', filename=job_info.job_id + '-funid_%d' % funid + '.png') }}" class="img-fluid" />
{% endif %}

<h3 id="function-matches">Matches for Function: {{ funid }}</h3>
<p>selection: {{ funp.max_value }}, showing: {{ 1 + funp.start_index }} - {{ funp.end_index }} (filtered: {{ matching_result.num_original_function_matches - funp.max_value}})</p>
<form class="form-inline" action ="{{ url_for(request.endpoint, **request.view_args) }}#function-matches" method='GET'>
  <div class="form-group row">
    <input type="hidden" id="funid" name="funid" value="{{ funid }}">
    <input type="hidden" id="funp" name="funp" value="{{ funp.page }}">
    <label class="col-6">Filter results to</label>
    <input class="col-3" type="text" name='filter_function_min_score' id="filter_function_min_score" aria-describedby="filter_function_min_score" placeholder="min score (0-100)" {% if matching_result.getFilterValue("filter_function_min_score") is not none %}value={{matching_result.getFilterValue("filter_function_min_score")}}{% endif %}>
    <input class="col-3" type="text" name='filter_function_max_score' id="filter_function_max_score" aria-describedby="filter_function_max_score" placeholder="max score (0-100)" {% if matching_result.getFilterValue("filter_function_max_score") is not none %}value={{matching_result.getFilterValue("filter_function_max_score")}}{% endif %}>
    <input class="col-1" type="checkbox" name='filter_exclude_pic' id="filter_exclude_pic" aria-describedby="filter_exclude_pic" {% if matching_result.getFilterValue("filter_exclude_pic") %}checked{% endif %}>
    <label class="col-3" for="block_count">exclude PIC hits</label>
    <button type="submit" class="btn btn-primary">filter</button>
  </div>
</form>
<table class="table table-hover">
  <thead class="thead-light">
    <tr>
    {% if ucs_functions is none %}
      {% set ucs_functions = ["function_id_a", "offset_a", "offset_b", "function_id_b", "family_name_b", "sample_id_b", "best_score", "is_minhash_match", "is_pichash_match", "is_library_match", "is_unique_match"] %}
    {% endif %}
    {% for column_type in ucs_functions %}
      {% if column_type == "function_id_a" %}
      <th scope="col">Function A&nbsp;<i class="fa-solid fa-project-diagram " title="Function ID"></th>
      {% elif column_type == "offset_a" %}
      <th style="text-align: right;" scope="col">Offset A</th>
      {% elif column_type == "offset_b" %}
      <th style="text-align: right;" scope="col">Offset B</th>
      {% elif column_type == "function_id_b" %}
      <th style="text-align: right;" scope="col">Function B&nbsp;<i class="fa-solid fa-project-diagram " title="Function ID"></th>
      {% elif column_type == "family_name_b" %}
      <th style="text-align: right;" scope="col">Family B&nbsp;<i class="fa-solid fa-bug " title="Family ID"></th>
      {% elif column_type == "sample_id_b" %}
      <th style="text-align: right;" scope="col">Sample B&nbsp;<i class="fa-solid fa-virus" title="Sample ID"></th>
      {% elif column_type == "best_score" %}
      <th style="text-align: right;" scope="col">Score</th>
      {% elif column_type == "is_minhash_match" %}
      <th style="text-align: center;" scope="col">Min</th>
      {% elif column_type == "is_pichash_match" %}
      <th style="text-align: center;" scope="col">Pic</th>
      {% elif column_type == "is_library_match" %}
      <th style="text-align: center;" scope="col">Lib</th>
      {% elif column_type == "is_unique_match" %}
      <th style="text-align: center;" scope="col">Uniq</th>
      {% endif %}
    {% endfor %}
    </tr>
  </thead>
  <tbody>
    {% for matched_function in matching_result.getFunctionsSlice(funp.start_index, funp.limit) %}
    <tr style="background-color:#{{ scp.getMatchHexColorFromResult(matched_function, 'matched_score', scale=50) }}">
      {% for column_type in ucs_functions %}
      {% if column_type == "function_id_a" %}
      <td valign="middle" scope="row" class="id"><a href="{{ url_for('explore.function_by_id', function_id=matched_function.function_id * -1 if matching_result.is_query else matched_function.function_id) }}">{% if matching_result.is_query %}*{% endif %}{{ matched_function.function_id }}</a>&nbsp;<a href="{{ url_for(request.endpoint, funid=matched_function.function_id, samp=1, funp=1, **request.view_args) }}#function-matches"><i class="fa-solid fa-filter"></i></a></td>
      {% elif column_type == "offset_a" %}
      <td style="text-align: right;" valign="middle">0x{{ "%x"|format(matched_function.offset) }}</td>
      {% elif column_type == "offset_b" %}
      <td style="text-align: right;" valign="middle">0x{{ "%x"|format(matched_function.matched_offset) }}</td>
      {% elif column_type == "function_id_b" %}
      <td style="text-align: right;" valign="middle"><a href="{{ url_for('explore.function_by_id', function_id=matched_function.matched_function_id) }}">{{ matched_function.matched_function_id }}</a>{% if not matching_result.is_query %}&nbsp;<a target="_blank" href="{{ url_for('data.match_functions', function_id_a=matched_function.function_id, function_id_b=matched_function.matched_function_id) }}"><i class="fa-solid fa-code-compare"></i></a>{% endif %}</td>
      {% elif column_type == "family_name_b" %}
      <td style="text-align: right;" valign="middle">{{ format_family_name(matching_result.getFamilyNameByFamilyId(matched_function.matched_family_id), matched_function.matched_family_id) }}</td>
      {% elif column_type == "sample_id_b" %}
      <td style="text-align: right;" valign="middle"><a href="{{ url_for('explore.sample_by_id', sample_id=matched_function.matched_sample_id) }}">{{ matched_function.matched_sample_id }}</a></td>
      {% elif column_type == "best_score" %}
      <td style="text-align: right;" valign="middle">{{ "%d"|format(matched_function.matched_score) }}</td>
      {% elif column_type == "is_minhash_match" %}
      <td style="text-align: center;" valign="middle"><i {% if matched_function.match_is_minhash %} style="color:green;" class="fa-solid fa-square-check" {% else %} style="color:darkred;" class="fa-solid fa-times-circle"> {% endif %}</i></td>
      {% elif column_type == "is_pichash_match" %}
      <td style="text-align: center;" valign="middle"><i {% if matched_function.match_is_pichash %} style="color:green;" class="fa-solid fa-square-check" {% else %} style="color:darkred;" class="fa-solid fa-times-circle"> {% endif %}</i></td>
      {% elif column_type == "is_library_match" %}
      <td style="text-align: center;" valign="middle"><i {% if matching_result.hasLibraryMatch(matched_function.function_id) %} style="color:green;" class="fa-solid fa-square-check" {% else %} style="color:darkred;" class="fa-solid fa-times-circle"> {% endif %}</i></td>
      {% elif column_type == "is_unique_match" %}
      <td style="text-align: center;" valign="middle"><i {% if matching_result.getFamilyIdsMatchedByFunctionId(matched_function.function_id)|length == 1 %} style="color:green;" class="fa-solid fa-square-check" {% else %} style="color:darkred;" class="fa-solid fa-times-circle"> {% endif %}</i></td>
      {% endif %}
      {% endfor %}
   </tr>
    {% endfor %}
  </tbody>
</table>

  {{ pagination_widget(funp, _anchor="function-matches")}}

<h3>Matching Method Statistics </h3>
{{ matching_statistics_table(matching_result.match_aggregation) }}

{% endblock %}

mcritweb/templates/result_corrupted.html
{% extends 'base.html' %}
{% block title%}
Results for Job: {{ job_info.job_id }} - corrupted!
{% endblock %}
{% block content %}

<h1>Results for Job: {{ job_info.job_id }} are corrupted :(</h1>

<p>{{reason}}</p>
<p>back to <a href="{{ url_for('data.jobs') }}">Jobs and Results</a></p>
<p><a href="{{"/data/jobs/" + job_info.job_id + "/delete"}}">Delete job data</a> and return back to Jobs and Results</p>

{% endblock %}

mcritweb/templates/submit.html
{% extends 'base.html' %}
{% block title%}
Submit
{% endblock %}
{% block style %}
{# no need to import these macros, they are already imported in base #}
{{ submit_or_query_dropzone_js(select_form_type=select_form_type) }}
{% endblock %}
{% set suppress_dropzone_overlay=true %}
{% block content %}
{{ submit_or_query_dropzone(select_form_type=select_form_type, show_submit_fields=show_submit_fields, families=families) }}
{% endblock %}