mcritweb/views/data.py
import os
import re
import datetime
import hashlib
import logging
from datetime import datetime
from mcrit.client.McritClient import McritClient
from mcrit.storage.MatchingResult import MatchingResult
from mcrit.storage.MatchedFunctionEntry import MatchedFunctionEntry
from mcrit.storage.FunctionEntry import FunctionEntry
from mcrit.storage.SampleEntry import SampleEntry
from mcrit.storage.UniqueBlocksResult import UniqueBlocksResult
from mcrit.queue.LocalQueue import Job
from smda.common.SmdaReport import SmdaReport
from flask import current_app, Blueprint, render_template, request, redirect, url_for, Response, flash, session, send_from_directory, json

from mcritweb.db import UserColumnSettings, UserFilters
from mcritweb.views.analyze import query as analyze_query
from mcritweb.views.utility import get_server_url, get_server_token, get_username, mcrit_server_required, parseBitnessFromFilename, parseBaseAddrFromFilename, get_matches_node_colors, parse_integer_query_param, parse_integer_list_query_param, parse_checkbox_query_param, parse_str_query_param, get_session_user_id
from mcritweb.views.pagination import Pagination
from mcritweb.views.cross_compare import get_sample_to_job_id, score_to_color
from mcritweb.views.authentication import visitor_required, contributor_required
from mcritweb.views.ScoreColorProvider import ScoreColorProvider
from mcritweb.views.MatchReportRenderer import MatchReportRenderer

bp = Blueprint('data', __name__, url_prefix='/data')

################################################################
# Helper functions
################################################################

def load_cached_result(app, job_id):
    matching_result = {}
    cache_path = os.sep.join([app.instance_path, "cache", "results"])
    for filename in os.listdir(cache_path):
        if job_id in filename and filename.endswith("json"):
            with open(cache_path + os.sep + filename, "r") as fin:
                matching_result = json.load(fin)
    return matching_result


def cache_result(app, job_info, matching_result):
    # TODO potentially implement a cache control that manages maximum allowed cache size?
    if job_info.result is not None:
        cache_path = os.sep.join([app.instance_path, "cache", "results"])
        timestamped_filename = datetime.utcnow().strftime(f"%Y%m%d-%H%M%S-{job_info.job_id}.json")
        with open(cache_path + os.sep + timestamped_filename, "w") as fout:
            json.dump(matching_result, fout, indent=1)


def create_match_diagram(app, job_id, matching_result, filtered_family_id=None, filtered_sample_id=None, filtered_function_id=None):
    cache_path = os.sep.join([app.instance_path, "cache", "diagrams"])
    filter_suffix = ""
    if filtered_family_id is not None:
        filter_suffix = f"-famid_{filtered_family_id}"
    elif filtered_sample_id is not None:
        filter_suffix = f"-samid_{filtered_sample_id}"
    elif filtered_function_id is not None:
        filter_suffix = f"-funid_{filtered_function_id}"
    output_path = cache_path + os.sep + job_id + filter_suffix + ".png"
    if not os.path.isfile(output_path):
        renderer = MatchReportRenderer()
        renderer.processReport(matching_result)
        image = renderer.renderStackedDiagram(filtered_family_id=filtered_family_id, filtered_sample_id=filtered_sample_id, filtered_function_id=filtered_function_id)
        image.save(output_path)
        print("stored new MCRIT diagram:", output_path)

# https://stackoverflow.com/a/39842765
# https://stackoverflow.com/a/26972238
# https://flask.palletsprojects.com/en/1.0.x/api/#flask.send_from_directory
@bp.route('/diagrams/<path:filename>')
def diagram_file(filename):
    cache_path = os.sep.join([current_app.instance_path, "cache", "diagrams"])
    return send_from_directory(cache_path, filename)


################################################################
# Import + Export
################################################################

@bp.route('/import',methods=('GET', 'POST'))
@mcrit_server_required
@contributor_required
def import_view():
    if request.method == 'POST':
        f = request.files.get('file', '')
        client = McritClient(mcrit_server=get_server_url(), apitoken=get_server_token(), username=get_username())
        session["last_import"] = client.addImportData(json.load(f))
    return render_template("import.html")

@bp.route('/import_complete')
@contributor_required
def import_complete():
    import_results = session.pop('last_import',{})
    if import_results:
        return render_template("import_complete.html", results=import_results)
    else:
        flash("This doesn't seem to be valid MCRIT data in JSON format", category='error')
        return render_template("import.html")


@bp.route('/export',methods=('GET', 'POST'))
@mcrit_server_required
@contributor_required
def export_view():
    if request.method == 'POST':
        requested_samples = request.form['samples']
        client = McritClient(mcrit_server=get_server_url(), apitoken=get_server_token(), username=get_username())
        if requested_samples == "":
            export_file = json.dumps(client.getExportData())
            return Response(
                export_file,
                mimetype='application/json',
                headers={"Content-disposition":
                        "attachment; filename=export_all_samples.json"})
        # NOTE it might be nice to allow [<number>, <number>-<number>, ...] to enable 
        # spans of consecutive sample_ids
        elif re.match("^\d+(?:[\s]*,[\s]*\d+)*$", requested_samples):
            sample_ids = [int(sample_id.strip()) for sample_id in requested_samples.split(',')]
            export_file = json.dumps(client.getExportData(sample_ids))
            return Response(
                export_file,
                mimetype='application/json',
                headers={"Content-disposition":
                        "attachment; filename=export_samples.json"})
        else:
            flash('Please use a comma-separated list of sample_ids in your export request.', category='error')
            return render_template("export.html")
    return render_template("export.html")

@bp.route('/specific_export/<type>/<item_id>')
@mcrit_server_required
@contributor_required
def specific_export(type, item_id):
    client = McritClient(mcrit_server=get_server_url(), apitoken=get_server_token(), username=get_username())
    if type == 'family':
        samples = client.getSamplesByFamilyId(item_id)
        sample_ids = [x.sample_id for x in samples.values()]
        export_file = json.dumps(client.getExportData(sample_ids))
        return Response(
            export_file,
            mimetype='application/json',
            headers={"Content-disposition":
                    "attachment; filename=export_family_"+str(item_id)+".json"})
    if type == 'samples':
        sample_ids = []
        sample_entry = client.getSampleById(item_id)
        if sample_entry:
            sample_ids.append(sample_entry.sample_id)
        export_file = json.dumps(client.getExportData(sample_ids))
        return Response(
            export_file,
            mimetype='application/json',
            headers={"Content-disposition":
                    "attachment; filename=export_samples.json"})

################################################################
# Direct Function Matching
################################################################

@bp.route('/matches/function/<function_id_a>/<function_id_b>')
@mcrit_server_required
@visitor_required
def match_functions(function_id_a, function_id_b):
    client = McritClient(mcrit_server=get_server_url(), apitoken=get_server_token(), username=get_username())
    if client.isFunctionId(function_id_a) and client.isFunctionId(function_id_b):
        match_info = client.getMatchFunctionVs(function_id_a, function_id_b)
        print(match_info)
        function_entry = FunctionEntry.fromDict(match_info["function_entry_a"])
        pichash_matches_a = client.getMatchesForPicHash(function_entry.pichash, summary=True)
        sample_entry_a = SampleEntry.fromDict(match_info["sample_entry_a"])
        other_function_entry = FunctionEntry.fromDict(match_info["function_entry_b"])
        sample_entry_b = SampleEntry.fromDict(match_info["sample_entry_b"])
        pichash_matches_b = client.getMatchesForPicHash(other_function_entry.pichash, summary=True)
        matched_function_entry = MatchedFunctionEntry(match_info["match_entry"]["fid"], match_info["match_entry"]["num_bytes"], match_info["match_entry"]["offset"], match_info["match_entry"]["matches"])
        node_colors = get_matches_node_colors(function_id_a, function_id_b)
        return render_template(
            "result_compare_function_vs.html",
            entry_a=function_entry,
            entry_b=other_function_entry,
            sample_entry_a=sample_entry_a,
            sample_entry_b=sample_entry_b,
            pichash_matches_a=pichash_matches_a,
            pichash_matches_b=pichash_matches_b,
            match_result=matched_function_entry,
            node_colors=json.dumps(node_colors)
        )
    flash("One of the function_ids is not valid.", category='error')
    return render_template("index.html")

################################################################
# Result presentation
################################################################

@bp.route('/result/<job_id>')
@mcrit_server_required
@visitor_required
# TODO:  refactor, simplify
def result(job_id):
    client = McritClient(mcrit_server=get_server_url(), apitoken=get_server_token(), username=get_username())
    # check if we have the respective report already locally cached
    result_json = load_cached_result(current_app, job_id)
    job_info = client.getJobData(job_id)
    if not result_json:
        # otherwise obtain result report from remote
        result_json = client.getResultForJob(job_id)
        if result_json:

mcritweb/templates/table/compare_nav.html
{% macro compare_nav(active) %}
<ul class="nav nav-pills justify-content-end">
  <li class="nav-item">
    <a class="nav-link {% if active=='1vsN' %}active{% endif %}" href="{{ url_for('analyze.compare') }}">1vsN</a>
  </li>
  <li class="nav-item">
    <a class="nav-link {% if active=='1vs1' %}active{% endif %}" href="{{ url_for('analyze.compare_versus') }}">1vs1</a>
  </li>
  <li class="nav-item">
    <a class="nav-link {% if active=='cross' %}active{% endif %}" href="{{ url_for('analyze.cross_compare') }}">Cross</a>
  </li>
  <li class="nav-item">
    <a class="nav-link {% if active=='query' %}active{% endif %}"  href="{{ url_for('analyze.query') }}">Query</a>
  </li>
</ul>
{% endmacro %}

mcritweb/templates/table/family_row.html
{% from 'table/pagination_widget.html' import sortable_header_col %}
{% from 'table/links.html' import format_pichash, format_offset, format_family_name, format_family_id, format_sample_id, format_function_id %}

{% macro family_row_std_js() %}
<script>
  $(document).ready(function(){
    var editFamilyModal = document.getElementById('editFamilyModal');
    editFamilyModal.addEventListener('show.bs.modal', function (event) {
    // Button that triggered the modal
    var button = event.relatedTarget;
    // Extract info from data-bs-* attributes
    var family_id = button.getAttribute('data-bs-familyid');
    var family_name = button.getAttribute('data-bs-familyname');
    var is_library = button.getAttribute('data-bs-islibrary');
    // Update the modal's content.
    var modalTitle = editFamilyModal.querySelector('.modal-title');
    var modalBodyFamilyName = editFamilyModal.querySelector('.modal-body #family_new_name');
    var modalBodyFamilyId = editFamilyModal.querySelector('.modal-body #family_id');
    var modalBodyLibrary = editFamilyModal.querySelector('.modal-body #family_is_library');
  
    modalTitle.textContent = 'Change Data for Family ' + family_id;
    modalBodyFamilyName.value = family_name;
    modalBodyFamilyId.value = family_id;
    if (is_library == "True") {
      modalBodyLibrary.checked = true;
    }
    else {
      modalBodyLibrary.checked = false;
    }
    })


    $("tr.family-row").click(function(e){
      console.log(e.target.name)
      if(event.target.id.includes("_edit")) {
      }
      else if(e.target.name === 'malpedia') {
        e.stopPropagation();
      }
      else{
        var family_id = $(this).children("th.id").text();
        if (family_id === ''){
          throw Error("Assertion failed")
        }
        window.location.href="{{ url_for('explore.families') }}"+ "/" + family_id;  
      }
    });
  });
</script>
{% endmacro %}


{% macro family_header(sort_pagination=None, column_setup=None) %}
  {# accept but discard additional kwargs #}
  {% if False %}{{ kwargs }}{% endif %}
  {% if column_setup is none %}
    {% set column_setup = ["family_id", "family_name", "num_samples", "num_functions", "is_library"] %}
  {% endif %}
  {% for column_type in column_setup %}
    {% if column_type == "family_id" %}
      {% call sortable_header_col(sort_pagination, "family_id") %}
        <i class="fa-solid fa-bug" title="Family ID"></i>
      {% endcall %}
    {% elif column_type == "family_name" %}
      {% call sortable_header_col(sort_pagination, "family_name") %}
        Family
      {% endcall %}
    {% elif column_type == "num_samples" %}
      {% call sortable_header_col(sort_pagination, "num_samples", align="right") %}
        Samples
      {% endcall %}
    {% elif column_type == "num_functions" %}
      {% call sortable_header_col(sort_pagination, "num_functions", align="right") %}
        Functions
      {% endcall %}
    {% elif column_type == "is_library" %}
      {% call sortable_header_col(sort_pagination, "num_library_samples", align="center") %}
        Library
      {% endcall %}
    {% endif %}
  {% endfor %}
    <th scope="col"></th>
  </tr>
{% endmacro %}  
  
{% macro family_row(family, show_export=False, show_edit=False, column_setup=None) %}
  {% if column_setup is none %}
    {% set column_setup = ["family_id", "family_name", "num_samples", "num_functions", "is_library"] %}
  {% endif %}
  <tr class="family-row parent_{{ kwargs['parent'] }}" >
  {% for column_type in column_setup %}
    {% if column_type == "family_id" %}
      <th align="right" valign="middle" class="id" scope="row">{{ "%d"|format(family.family_id) }}</th>
    {% elif column_type == "family_name" %}
      <td valign="middle" >{{ format_family_name(family.family_name, None) }}<a name="malpedia" href="https://malpedia.caad.fkie.fraunhofer.de/details/{{ family.family }}" target="_blank"><i class="fa-solid fa-external-link-alt "></i></a></td>
    {% elif column_type == "num_samples" %}
      <td align="right" valign="middle">{{ "%d"|format(family.num_samples) }}</td>
    {% elif column_type == "num_functions" %}
      <td align="right" valign="middle">{{ "%d"|format(family.num_functions) }}</td>
    {% elif column_type == "is_library" %}
      <td align="center" valign="middle"><i {% if family.is_library %} style="color:green;" class="fa-solid fa-square-check" {% else %} style="color:darkred;" class="fa-solid fa-times-circle"> {% endif %}</i></td>
    {% endif %}
  {% endfor %}
    <td align="center" valign="middle">
      <a class="btn btn-outline-dark btn-sm" name="compare" href="{{ url_for('analyze.compare', query=family.family_name, rematch='true') }}" role="button" target="_self"><i class="fa-solid fa-flask"></i></a>
      <a class="btn btn-outline-dark btn-sm" name="family_blocks" href="{{ url_for('analyze.blocks_family', family_id=family.family_id) }}" role="button" target="_self"><i class="fa-solid fa-cubes-stacked"></i></a>
      {% if show_export %}
        <a class="btn btn-outline-dark btn-sm" href="{{ url_for('data.specific_export', type='family', item_id=family.family_id) }}" role="button" target="_self"><i class="fa-solid fa-file-export"></i></a>
      {% endif %}
      {% if show_edit %}
      <a class="btn btn-outline-dark btn-sm" id="sample_{{ family.family_id }}_edit" role="button" data-bs-toggle="modal" data-bs-target="#editFamilyModal" data-bs-islibrary="{{ family.is_library }}"  data-bs-familyid="{{ family.family_id }}" data-bs-familyname="{{ family.family_name }}"><i class="fa-solid fa-pen-to-square"></i></a>
    {% endif %}
    </td>
  </tr>
{% endmacro %}  

mcritweb/templates/table/matching_statistics_table.html
{% macro matching_statistics_table(match_aggregation) %}
  {% set fields = [
    'num_own_functions_matched',
    'num_foreign_functions_matched',
    'num_own_functions_matched_as_library',
    'num_self_matches',
    'bytes_matched',
  ] %}
  
  <table class="table table-hover">
    <thead class="thead-light">
      <tr>
        <th scope="col">Field</th>
        <th style="text-align: right;" scope="col">MinHash</th>
        <th style="text-align: right;" scope="col">PicHash</th>
      </tr>
    </thead>
    <tbody>
      {% for field in fields %}
        <tr>
          <td valign="middle">{{ field }}: </td>
          <td style="text-align: right;" valign="middle">{{ match_aggregation["minhash"][field] }}</td>
          <td style="text-align: right;" valign="middle">{{ match_aggregation["pichash"][field] }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endmacro %}

mcritweb/templates/table/sample_row.html
{% from 'table/pagination_widget.html' import sortable_header_col %}
{% from 'table/links.html' import format_pichash, format_offset, format_family_name, format_family_id, format_sample_id, format_function_id %}

{% macro sample_row_std_js() %}
<script>
  var button_clicked = false;
  
  $(document).ready(function(){
    var editSampleModal = document.getElementById('editSampleModal');
    editSampleModal.addEventListener('show.bs.modal', function (event) {
    // Button that triggered the modal
    var button = event.relatedTarget;
    // Extract info from data-bs-* attributes
    var family_name = button.getAttribute('data-bs-familyname');
    var sample_id = button.getAttribute('data-bs-sampleid');
    var version = button.getAttribute('data-bs-version');
    var is_library = button.getAttribute('data-bs-islibrary');
    // Update the modal's content.
    var modalTitle = editSampleModal.querySelector('.modal-title');
    var modalBodyFamilyName = editSampleModal.querySelector('.modal-body #sample_family_name');
    var modalBodyVersion = editSampleModal.querySelector('.modal-body #sample_version');
    var modalBodySampleId = editSampleModal.querySelector('.modal-body #sample_id');
    var modalBodyLibrary = editSampleModal.querySelector('.modal-body #sample_is_library');
  
    modalTitle.textContent = 'Change Data for Sample ' + sample_id;
    modalBodyFamilyName.value = family_name;
    modalBodyVersion.value = version;
    modalBodySampleId.value = sample_id;
    if (is_library == "True") {
      modalBodyLibrary.checked = true;
    }
    else {
      modalBodyLibrary.checked = false;
    }
    })

    $("tr.sample-row").click(function(e){
    if(event.target.id.includes("_edit")) {
    }
    else if(button_clicked) {
      e.stopPropagation();
      button_clicked = false;
      own_menu = $(this).find('#dropdown-menu');
      was_visible = own_menu.is(":visible");
      $("tr.sample-row").find('#dropdown-menu').hide();
      if (!was_visible){
        $(this).find('#dropdown-menu').toggle();
      }
    }
    else{
      var sample_id = $(this).children("th.sample-id").text();
      window.location.href="{{ url_for('explore.samples') }}"+ "/" + sample_id;
    }
    });
  });
  function set_analyze_sample_button_clicked() {
    button_clicked = true;
  }
</script>
{% endmacro %}



{% macro sample_header(no_family=False, compact_view=False, show_analyze=True, show_export=False, show_hint=False, show_edit=False, sort_pagination=None, column_setup=None) %}
  {# accept but discard additional kwargs #}
  {% if False %}{{ kwargs }}{% endif %} 
  {% if column_setup is none %}
    {% set column_setup = ["sample_id", "sha256", "family", "version", "filename", "bitness", "num_functions", "is_library"] %}
  {% endif %}
  <tr>
    {% for column_type in column_setup %}
      {% if column_type == "sample_id" %}
        {% call sortable_header_col(sort_pagination, "sample_id") %}
          <i class="fa-solid fa-virus" title="Sample ID"></i>
        {% endcall %}
      {% elif column_type == "sha256" %}
        {% call sortable_header_col(sort_pagination, "sha256", align="right") %}
          SHA256
        {% endcall %}
      {% elif column_type == "family" %}
        {% if not no_family %}
          {% call sortable_header_col(sort_pagination, "family") %}
            Family
          {% endcall %}
        {% endif %}
      {% elif column_type == "version" and not compact_view %}
        {% call sortable_header_col(sort_pagination, "version") %}
          Version
        {% endcall %}
      {% elif column_type == "filename" and not compact_view %}
        {% call sortable_header_col(sort_pagination, "filename") %}
          Filename
        {% endcall %}
      {% elif column_type == "bitness" and not compact_view %}
        <th style="text-align: right;" scope="col">Bitness</th>
      {% elif column_type == "num_functions" %}
        {% call sortable_header_col(sort_pagination, "statistics.num_functions", align="right") %}
          Functions
        {% endcall %}
      {% elif column_type == "is_library" %}
        <th style="text-align: right;" scope="col">Library</th>
      {% endif %}
    {% endfor %}
    {% if show_hint %}
      <th scope="col"></th>
    {% endif %}
    {% if (show_export or show_analyze or show_edit) %}
      <th scope="col"></th>
    {% endif %}
  </tr>
{% endmacro %}
  
  
{% macro sample_row(sample, no_family=False, compact_view=False, show_analyze=True, show_export=False, show_edit=False, show_hint=False, job_collection=None, column_setup=None) %}
  {% if column_setup is none %}
    {% set column_setup = ["sample_id", "sha256", "family", "version", "filename", "bitness", "num_functions", "is_library"] %}
  {% endif %}
  <tr class="sample-row parent_{{ kwargs['parent'] }}" >
    {% for column_type in column_setup %}
      {% if column_type == "sample_id" %}
       <th align="left" valign="middle" scope="row" class="sample-id">{{ "%d"|format(sample.sample_id) }}</th>
      {% elif column_type == "sha256" %}
        <td align="right" valign="middle" class="font-monospace">{{ sample.getShortSha256() }}</td>
      {% elif column_type == "family" %}
        {% if not no_family %}
          <td valign="middle">{{ format_family_name(sample.family, sample.family_id) }}</td>
        {% endif %}
      {% elif column_type == "version" and not compact_view %}
        <td valign="middle">{{ sample.version }}</td>
      {% elif column_type == "filename" and not compact_view %}
        <td valign="middle">{{ sample.getShortFilename() }}</td>
      {% elif column_type == "bitness" and not compact_view %}
        <td align="right" valign="middle">{{ "%d"|format(sample.bitness) }}</td>
      {% elif column_type == "num_functions" %}
        <td align="right" valign="middle">{{ "%d"|format(sample.statistics['num_functions']) }}</td>
      {% elif column_type == "is_library" %}
        <td align="center" valign="middle"><i {% if sample.is_library %} style="color:green;" class="fa-solid fa-square-check" {% else %} style="color:darkred;" class="fa-solid fa-times-circle"> {% endif %}</i></td>
      {% endif %}
    {% endfor %}
    {% if show_hint %}
      <td>
        <span class="hint--left" data-hint="Sample_ID: {{ sample.sample_id }}&#10;SHA256: {{ sample.sha256 }}&#10;Family: {{ sample.family }}&#10;Version: {{ sample.version }}&#10;Filename: {{ sample.filename }} &#10;Architecture: {{ sample.architecture }}&#10;Bitness: {{ sample.bitness }} &#10;Base_Address: 0x{{ '%0x' % sample.base_addr }}&#10;Binary_Size: {{ '{:,.0f}'.format(sample.binary_size) }}&#10;Binweight: {{ '{:,.0f}'.format(sample.binweight) }}"><i class="fa-solid fa-circle-info"></i></span>
      </td>
    {% endif %}
    {% if (show_export or show_analyze) %}
      <td align="right" class="buttons">
        {% if show_analyze %}
          <button type="button" class="btn btn-outline-dark btn-sm" id="sample_{{ sample.sample_id }}_analyze" onclick=set_analyze_sample_button_clicked() bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {% if job_collection and job_collection.getJobsForSample(sample.sample_id, matching_only=True) %}
            <i style="color:green;" class="fa-solid fa-flask"></i>&nbsp;{{ job_collection.getJobsForSample(sample.sample_id, matching_only=True) | length}}
            {% else %}
            <i class="fa-solid fa-flask"></i>
            {% endif %}
          </button>
          <div class="dropdown-menu dropdown-menu-end" id="dropdown-menu">
            <a class="dropdown-item" href="{{ url_for('analyze.compare', query='sha256:'+sample.sha256) }}">New: 1 vs N</a>
            <a class="dropdown-item" href="{{ url_for('analyze.compare_versus', selected_a=sample.sample_id, query_a='sha256:'+sample.sha256) }}">New: 1 vs 1</a>
            <a class="dropdown-item" href="{{ url_for('analyze.cross_compare', samples=sample.sample_id) }}">Cross Compare</a>
            <a class="dropdown-item" href="{{ url_for('explore.sample_by_id', sample_id=sample.sample_id, _anchor='jobs') }}">Previous Jobs</a>
            {% if job_collection and job_collection.getJobsForSample(sample.sample_id, method="getMatchesForSample", finished_only=True) %}
            <a class="dropdown-item" href="{{ url_for('data.result', job_id=job_collection.getJobsForSample(sample.sample_id, method="getMatchesForSample", finished_only=True)[0].job_id) }}">Last 1:N Job</a>
            {% endif %}
          </div>
        {% endif %}
        {% if show_analyze %}
          <a class="btn btn-outline-dark btn-sm" id="sample_{{ sample.sample_id }}_family_blocks" href="{{ url_for('analyze.blocks_sample', sample_id=sample.sample_id) }}" role="button" target="_self"><i class="fa-solid fa-cubes-stacked"></i></a>
        {% endif %}
        {% if show_export %}
          <a class="btn btn-outline-dark btn-sm" id="sample_{{ sample.sample_id }}_export" href="{{ url_for('data.specific_export', type='samples', item_id=sample.sample_id) }}" role="button" target="_self"><i class="fa-solid fa-file-export"></i></a>
        {% endif %}
        {% if show_edit %}
          <a class="btn btn-outline-dark btn-sm" id="sample_{{ sample.sample_id }}_edit" role="button" data-bs-toggle="modal" data-bs-target="#editSampleModal" data-bs-islibrary="{{ sample.is_library }}"  data-bs-version="{{ sample.version }}"  data-bs-sampleid="{{ sample.sample_id }}" data-bs-familyname="{{ sample.family }}"><i class="fa-solid fa-pen-to-square"></i></a>
        {% endif %}
      </td>
    {% endif %}
  </tr>

{% endmacro %}


{% macro minisample_header(no_family=False, compact_view=False, show_analyze=True, show_export=False, show_hint=False, show_edit=False, sort_pagination=None) %}
  <tr>
    <th style="min-width: 90px;">
      Uploaded
    </th>
    <th>
      <i class="fa-solid fa-virus" title="Sample ID"></i>
    </th>
    <th>
      SHA256
    </th>
    <th>
      Family
    </th>
    <th>
      Version
    </th>
    <th>
      Filename
    </th>
  </tr>
{% endmacro %}

{% macro minisample_row(sample, no_family=False, compact_view=False, show_analyze=True, show_export=False, show_edit=False, show_hint=False, job_collection=None) %}
  <tr class="sample-row parent_{{ kwargs['parent'] }}" >
    <td>{{ sample.timestamp|date }}</td>
    <td align="left" valign="middle" scope="row" class="sample-id">{{ format_sample_id(sample.sample_id) }}</td>
    <td align="right" valign="middle" class="font-monospace">{{ sample.getShortSha256() }}</td>
    <td valign="middle">{{ format_family_name(sample.family, sample.family_id) }}</td>
    <td valign="middle">{{ sample.version }}</td>
    <td valign="middle">{{ sample.getShortFilename() }}</td>
  </tr>
{% endmacro %}